spring:
    jpa:
        hibernate:
            ddl-auto: create
    # master datasource
    master:
        datasource:
            jdbc-url: jdbc:h2:mem:masterdb;DB_CLOSE_DELAY=-1
            username: sa
            password:
            driver-class-name: org.h2.Driver
            initialization-mode: always
            #        datasource:
            #            driver-class-name: com.mysql.jdbc.Driver
            #            jdbc-url: jdbc:mysql://
            #            username:
            #            password:
        h2:
            console:
                enabled: true
                settings:
                    web-allow-others: true
    # slave datasource
    slave:
        ignore: false
        datasource:
            jdbc-url: jdbc:h2:mem:slavedb;DB_CLOSE_DELAY=-1
            username: sa
            password:
            driver-class-name: org.h2.Driver
        h2:
            console:
                enabled: true
                settings:
                      web-allow-others: true

#    slave:
#        ignore: false
#        datasource:
#            driver-class-name: com.mysql.jdbc.Driver
#            jdbc-url: jdbc:mysql://
#            username:
#            password:
